### ISSUE TITLE
Add capabilities for securityContext

### ISSUE THREAD

**Issue by Whi7y** [neo4j/helm-charts#103]
Hello

Currently we cannot set up Neo4j on our Kubernetes cluster because we have a restriction from Kyverno where the capabilities have to be dropped.

A fix would be to add 'capabilities' in *values.yaml*. Here for example 'dropping all':
```yaml
securityContext:
  runAsNonRoot: true
  runAsUser: 7474
  runAsGroup: 7474
  fsGroup: 7474
  fsGroupChangePolicy: "Always"
  capabilities:
    drop: ["ALL"]
```

https://kubernetes.io/docs/tasks/configure-pod-container/security-context/

The securityContext is used at both the pod and container level. When I add the capabilities, I get the error message that this configuration does not exist at the pod level. Because of that the template *neo4j-statefulset.yaml* would have to be adjusted, because the capabilities are only on the container level. Therefore, those at the pod level must be omitted. Maybe like this:

```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  template:
    metadata:
      securityContext: {{ omit .Values.securityContext "capabilities" | toYaml | nindent 8 }}
[...]
```

Thanks
