### ISSUE TITLE
custom podAntiAffinity rules

### ISSUE THREAD

**Issue by olympe-operator** [neo4j/helm-charts#149]
**Is your feature request related to a problem? Please describe.**
Using the deprecated helm chart, it was possible to setup a custom `podAntiAffinity` rule. with this one it's not possible anymore (at least for 4.4, which is the version we are using)

**Describe the solution you'd like**
We have a EKS cluster splitted in 3 AZ. Using the deprecated helm chart we used to setup a `podAntiAffinity` rule to avoid having 2 pods on the same zone:
```
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100  
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/instance
                operator: In
                values:
                - neo4j-cluster
          topologyKey: "topology.kubernetes.io/zone"
```
with the limited boolean `podAntiAffinity` value of this chart, we cannot do that anymore because the `topologyKey: kubernetes.io/hostname`  is not enough for our needs, as 2 pods  could be created on different hosts in the same zone

**Describe alternatives you've considered**
I don't see any alternative except adding a `customPodAntiAffinity` rule, so it doesn't break the current behavior for backward compatibility
