### ISSUE TITLE
[Bug]: neo4j duplicate mapping key at ConfigMap (default-config)

### ISSUE THREAD

**Issue by StiviiK** [neo4j/helm-charts#160]
### What happened?

If you render the [neo4j](https://github.com/neo4j/helm-charts/tree/dev/neo4j) helm chart using helm template using a minimal values.yaml (taken from the example):
```yaml
neo4j:
  name: neo4j
  resources:
    cpu: "0.5"
    memory: "2Gi"

  # Uncomment to set the initial password
  #password: "my-initial-password"

  # Uncomment to use enterprise edition
  #edition: "enterprise"
  #acceptLicenseAgreement: "yes"

volumes:
  data:
    mode: "dynamic"
    dynamic:
      # * managed-csi-premium provisions premium SSD disks (recommended)
      # * managed-csi provisions standard SSD-backed disks
      storageClassName: managed-csi-premium
```

It leads to a duplicate mapping key for `server.directories.import` & `server.jvm.additional` in the ConfigMap.
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: "my-neo4j-release-default-config"
  namespace: "simulation"
  labels:
    app: "my-standalone"    
data:

  # Neo4j defaults
  server.directories.import: import
  [...]
  server.jvm.additional: -XX:+UseG1GC
  server.jvm.additional: -XX:-OmitStackTraceInFastThrow
  server.jvm.additional: -XX:+AlwaysPreTouch
  server.jvm.additional: -XX:+UnlockExperimentalVMOptions
  server.jvm.additional: -XX:+TrustFinalNonStaticFields
  server.jvm.additional: -XX:+DisableExplicitGC
  server.jvm.additional: -Djdk.nio.maxCachedBufferSize=1024
  server.jvm.additional: -Dio.netty.tryReflectionSetAccessible=true
  server.jvm.additional: -Djdk.tls.ephemeralDHKeySize=2048
  server.jvm.additional: -Djdk.tls.rejectClientInitiatedRenegotiation=true
  server.jvm.additional: -XX:FlightRecorderOptions=stackdepth=256
  server.jvm.additional: -XX:+UnlockDiagnosticVMOptions
  server.jvm.additional: -XX:+DebugNonSafepoints
  server.jvm.additional: --add-opens=java.base/java.nio=ALL-UNNAMED
  server.jvm.additional: --add-opens=java.base/java.io=ALL-UNNAMED
  server.jvm.additional: --add-opens=java.base/sun.nio.ch=ALL-UNNAMED
  server.jvm.additional: -Dlog4j2.disable.jmx=true
  [...]
  server.directories.import: "/import"
```

When trying to deploy this Chart via FluxCD it leads to Helm install errors.

### Chart Name

Standalone

### Chart Version

5.5.0

### Environment

FluxCD, Kustomize

### Relevant log output

```shell
Status:                                                                                                                                                                                                                                                                      │
│   Conditions:                                                                                                                                                                                                                                                                │
│     Last Transition Time:  2023-03-30T10:17:39Z                                                                                                                                                                                                                              │
│     Message:               Helm install failed: error while running post render on files: map[string]interface {}(nil): yaml: unmarshal errors:                                                                                                                              │
│   line 55: mapping key "server.directories.import" already defined at line 14                                                                                                                                                                                                │
│   line 20: mapping key "server.jvm.additional" already defined at line 19                                                                                                                                                                                                    │
│   line 21: mapping key "server.jvm.additional" already defined at line 19
```

### Relevant Issues
https://github.com/fluxcd/flux2/issues/1522

```
Duplicate YAML keys

Unlike Helm, the Kustomize yaml parser (kyaml) does not accept duplicate keys, while Helm drops the duplicates, Kustomize errors out. This impacts helm-controller as it uses kustomize/kyaml to label objects reconciled by a HelmRelease.

For example, a chart that adds the app.kubernetes.io/name more than once, will result in a HelmRelease install failure:

map[string]interface {}(nil): yaml: unmarshal errors:
line 21: mapping key "app.kubernetes.io/name" already defined at line 20
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
