### ISSUE TITLE
[Bug]: Unable to configure APOC

### ISSUE THREAD

**Issue by bitflingr** [neo4j/helm-charts#171]
### Contact Details

jarrett@whoco.com

### What happened?

With Plugins installed and loaded successfully
```
RETURN apoc.version()
apoc.version()
--
1 | "4.4.0.7"
```

I try and set `apoc.export.file.enabled: "true"` using `apoc_config` as well as `env:` in my helm chart but neither one seems to affect the running config.
```
CALL dbms.listConfig()
YIELD name, value, dynamic
WHERE name STARTS WITH 'apoc'
RETURN name, value, dynamic
ORDER BY name;
// LIMIT 3;

name | value | dynamic
-- | -- | --
1 | "apoc.export.file.enabled" | "false" | false
2 | "apoc.import.file.enabled" | "false" | false
3 | "apoc.import.file.use_neo4j_config" | "true" | false
```

I have verified the environment variable is set:
```
$ env | grep apoc
NEO4J_apoc_import_file_enabled=true
NEO4J_apoc_export_file_enabled=true
```
and verified that apoc.conf is generated and mounted in the pod:
```
$ ls /config
apoc.conf  neo4j.conf
$ cat /config/apoc.conf
apoc.export.file.enabled=true
apoc.jdbc.apoctest.url=jdbc:foo:bar
```

Here is a snippet of the values.yaml that have so far.
```yaml
config:
  dbms.directories.plugins: "/plugins"
  dbms.security.procedures.unrestricted: "jwt.security.*,apoc.*,gds.*,n10s.*"
  dbms.security.procedures.allowlist: "jwt.security.*,apoc.*,gds.*,n10s.*"
  server.config.strict_validation.enabled: "false"

apoc_config:
  apoc.export.file.enabled: "true"
  apoc.jdbc.apoctest.url: "jdbc:foo:bar"

env: 
  NEO4J_apoc_import_file_enabled: "true"
  NEO4J_apoc_export_file_enabled: "true"
```
Am I missing a key config?

### Chart Name

Standalone

### Chart Version

4.4.18

### Environment

Amazon Web Services

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bitflingr** [comment]
oh and I am using helm chart 4.4.19

**Comment by harshitsinghvi22** [comment]
Hi @bitflingr 

Thanks for reporting this issue.

This is a known bug with apoc latest jar with the dbms.listConfig() does not show the apoc configs. The respective team is working on fixing it.

However , meanwhile you can use the apoc.*full.jar to load the apoc config via apoc.config.list() function.

Neo4j is prepackaged with apoc core jar and not full jar . You can download the full jar from [here](https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/download/4.4.0.15/apoc-4.4.0.15-all.jar) and put it in the desired location on your neo4j pod via kubectl cp command or using a custom docker image or init container. You can read about them [here](https://neo4j.com/docs/operations-manual/4.4/kubernetes/configuration/#operations-installing-plugins)

Once neo4j is up and running with the above apoc full jar you can verify the configs with 
```
CALL apoc.config.list() YIELD key , value;
```
Also the below config looks wrong , this works for Neo4j 5 
```
server.config.strict_validation.enabled: "false"
```
For Neo4j 4.4 the correct config will be 
```
dbms.config.strict_validation: "false"
```

**Comment by bitflingr** [comment]
Thanks @harshitsinghvi22 for the reply.  Unfortunately we are using the full version of the apoc jar plugin. 
Here is the jars uploaded to the image:
```bash
apoc-4.4.0.7-all.jar
apoc-nlp-dependencies-4.4.0.7.jar
apoc-xls-dependencies-4.4.0.7.jar
aws-java-sdk-core-1.12.197.jar
aws-java-sdk-s3-1.12.197.jar
aws-java-sdk-sts-1.12.197.jar
httpclient-4.5.4.jar
httpcore-4.4.8.jar
joda-time-2.9.9.jar
neo4j-extensions-1.0.0.jar
neo4j-graph-data-science-2.3.1.jar
neosemantics-4.4.0.1.jar
```

Is the fix in 4.4.0.15 version of apoc-all?

**Comment by harshitsinghvi22** [comment]
@bitflingr I  would recommend using 4.4.0.15 version of apoc all... this is the jar that comes packaged with neo4j 4.4.19...I would suggest you to use the apoc jar which is packaged with neo4j

**Comment by harshitsinghvi22** [comment]
@bitflingr you can also try the below values.yaml

```
neo4j:
  
  name: "demo2"
  
  resources:
    cpu: "0.5"
    memory: "2Gi"

  # Uncomment to set the initial password
  password: "password"

  # Uncomment to use enterprise edition
  edition: "community"
  acceptLicenseAgreement: "no"

volumes:
  # plugins:
  #   mode: "dynamic"
  #   dynamic:
  #     storageClassName: "standard-rwo"
  #     accessModes:
  #       - ReadWriteOnce
  #     requests:
  #       storage: 10Gi      
  data:
    mode: "defaultStorageClass"

env:
  NEO4J_PLUGINS: '[ "apoc" ]'    

config:
  dbms.directories.plugins: "/var/lib/neo4j/plugins"
  dbms.security.procedures.unrestricted: "jwt.security.*,apoc.*,gds.*,n10s.*"
  dbms.security.procedures.allowlist: "jwt.security.*,apoc.*,gds.*,n10s.*"
  dbms.config.strict_validation: "false"

apoc_config:
  apoc.export.file.enabled: "true"
  apoc.import.file.enabled: "true"
  apoc.jdbc.apoctest.url: "jdbc:foo:bar"


```

The NEO4J_PLUGINS env variable will download the apoc.jar (full) at /var/lib/neo4j/plugins and you can use that to run the apoc.config.list() command to verify the apoc configs. I have tried the above and it works fine

![Screenshot 2023-04-27 at 11 24 40](https://user-images.githubusercontent.com/89837129/234835359-684988e2-7702-4265-8df4-368489ff8949.png)
