### ISSUE TITLE
[Bug]: imagePullSecret not created correctly with disableLookups

### ISSUE THREAD

**Issue by grantat** [neo4j/helm-charts#190]
### What happened?

Running `helm template` with an imagePullSecret (that already exists) set and `disableLookups` set to true generates a secret with no name.  To reproduce, use the following `values.yaml`:

```yaml
disableLookups: true
neo4j:
  name: "neo4j"
  passwordFromSecret: "auth-secret"
  edition: "community"
image:
  imagePullSecrets:
    - "pull-secret"
volumes:
  data:
    mode: "defaultStorageClass"
```

Use the following helm command to inspect the kubernetes manifests:

```bash
helm template neo4j/neo4j-standalone --version 4.4.18 --namespace test --values values.yaml --debug
```

Ideally, the new imagePullSecret would not be created and would instead use the existing imagePullSecret as defined by the `values.yaml`.

Related to #154 

### Chart Name

Standalone

### Chart Version

4.4.18

### Environment

Local Machine

### Relevant log output

```shell
---
# Source: neo4j-standalone/templates/neo4j-imagePullSecret.yaml
apiVersion: v1
kind: Secret
metadata:
   name: ""
   namespace: "test"
   labels:
     app: "neo4j"    
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ...
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by harshitsinghvi22** [comment]
thanks for reporting this @grantat ...Looking into this

**Comment by harshitsinghvi22** [comment]
this is fix in the below PR and will be part of the next release

https://github.com/neo4j/helm-charts/pull/193

**Comment by harshitsinghvi22** [comment]
fixed in 5.x too and will be part of the next release
https://github.com/neo4j/helm-charts/pull/194

**Comment by grantat** [comment]
Hi @harshitsinghvi22, thanks for the quick response. However, if I'm understanding the proposed fix in #193 / #194, the Secret defined in https://github.com/neo4j/helm-charts/blob/fade332ca65677953ebf5382415419232980e5ce/neo4j/templates/neo4j-imagePullSecret.yaml would still be attempted to be created. I've already defined an imagePullSecret `pull-secret` and there is no need for the neo4j helm chart to create another resource of type `Secret` which would not be used by any of the remaining manifests. Maybe you can extend the `$.Values.disableLookups` conditional on https://github.com/neo4j/helm-charts/blob/fade332ca65677953ebf5382415419232980e5ce/neo4j/templates/neo4j-imagePullSecret.yaml#L15-L18 to be:

```yaml
      {{- if not $.Values.disableLookups -}}
        {{- $secret := (lookup "v1" "Secret" $.Release.Namespace $imagePullSecret) -}}
        {{- $secretExists = $secret | all -}}
      {{- else }}
         {{- $secretExists := true }} 
      {{- end -}}
```
as the neo4j chart does not have the ability to determine if the imagePullSecret already exists without lookups enabled.

**Comment by harshitsinghvi22** [comment]
Hi @grantat since the disableLookups is set to true helm chart does not know if the secret exists hence the behaviour is correct where it assumes the secret is missing (incase of disableLookups set to true) and it will create the secret manifest

However , if you execute the same thing with helm install (setting disableLookups to false) it will not create secret since it will check for the secret existence and will find the same.

**Comment by hpdobrica** [comment]
hello @harshitsinghvi22, i'm in a similar pickle as @grantat, and was wondering whether it'd make sense/be possible for us to rely on the lack of provided `values.image.imageCredentials` to know that the secret should not be created, even if the lookup is disabled?

I was under the impression that this is the intended behavior, since values comment on imageCredentials says "In case of a secret already pre-existing you don't need to mention the imageCredential , just add the pre-existing secretName to the imagePullSecret list and that will be used as an imagePullSecret"

I expected the value provided by `include "neo4j.imageCredentials.getImageCredential` to be empty as i haven't provided anything in imageCredentials values, but instead i got a secret with no name and docker config that looks like this:

`{"auths":{"%!s(<nil>)":{"username":"%!s(<nil>)","password":"%!s(<nil>)","email":"%!s(<nil>)","auth":"JSFzKDxuaWw+KTolIXMoPG5pbD4p"}}}`

my values look like this:
```yaml
  image:
    imagePullPolicy: IfNotPresent
    imagePullSecrets:
      - "sysdigcloud-pull-secret"
```

and rendered image looks like this:
```yaml
# Source: neo4j/charts/neo4j/templates/neo4j-imagePullSecret.yaml
apiVersion: v1
kind: Secret
metadata:
   name: ""
   namespace: "neo4j-helm-test"
   labels:
     app: "neo4j-cluster"    
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: eyJhdXRocyI6eyIlIXMoPG5pbD4pIjp7InVzZXJuYW1lIjoiJSFzKDxuaWw+KSIsInBhc3N3b3JkIjoiJSFzKDxuaWw+KSIsImVtYWlsIjoiJSFzKDxuaWw+KSIsImF1dGgiOiJKU0Z6S0R4dWFXdytLVG9sSVhNb1BHNXBiRDRwIn19fQ==

```
