### ISSUE TITLE
[Bug]: Loadbalancer annotations are templated to labels instead

### ISSUE THREAD

**Issue by nic-bor** [neo4j/helm-charts#202]
### What happened?

When trying to annotate the loadbalancer service, the annotations are instead included under the "labels" section.

Given these values:
```yaml
...
services:
  neo4j:
    annotations:
      annotation1: "val1"
      annotation2: "val2"
```

Running `helm template --debug neo4j/neo4j -f values.yaml -s templates/neo4j-loadbalancer.yaml `, the output is:

```
apiVersion: v1
kind: Service
metadata:
  name: "neo4j-lb-neo4j"
  namespace: "default"
  labels:
    helm.neo4j.com/neo4j.name: "neo4j"
    app: "neo4j"
    helm.neo4j.com/service: "neo4j"
    annotation1: "val1"
    annotation2: "val2"
```

While the expected output is:
```
apiVersion: v1
kind: Service
metadata:
  name: "neo4j-lb-neo4j"
  namespace: "default"
  labels:
    helm.neo4j.com/neo4j.name: "neo4j"
    app: "neo4j"
    helm.neo4j.com/service: "neo4j"
  annotations:
    annotation1: "val1"
    annotation2: "val2"
```

### Chart Name

Standalone

### Chart Version

5.5.0

### Environment

Microsoft Azure

### Relevant log output

```shell
See description
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
