### ISSUE TITLE
Statefullset via replicas, not independ deployment

### ISSUE THREAD

**Issue by mixMugz** [neo4j/helm-charts#207]
**Is your feature request related to a problem? Please describe.**

In the current implementation, each cluster instance is deployed through a separate chart installation. I suggest using a standalone cluster installation and managing the number of statefulset replicas in the cluster.

**Describe the solution you'd like**
All you need to do:
- depending on the number of replicas specified in values.yaml, create a multiple number of services according to the template <name>-<suffix>, in the selector we bind to statefulset.kubernetes.io/pod-name:
- In the Statefullset we edit the variables:
```
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: SERVICE_NEO4J_ADMIN
          value: $(POD_NAME)-admin.neo4j.svc.cluster.local
        - name: SERVICE_NEO4J_INTERNALS
          value: $(POD_NAME)-internals.neo4j.svc.cluster.local
        - name: SERVICE_NEO4J
          value: $(POD_NAME).neo4j.svc.cluster.local
```
