### ISSUE TITLE
[Bug]: Neo4j v5 Cluster when using neo4j helm chart as a dependency

### ISSUE THREAD

**Issue by psolarcz** [neo4j/helm-charts#209]
### What happened?

While checking a Neo4j docs for cluster setup: https://neo4j.com/docs/operations-manual/5/kubernetes/quickstart-cluster/install-servers/ I discovered that we have to install the same chart 3 times with different names. Is there a way to create a cluster when using neo4j helm chart as a dependency of our own chart?

### Chart Name

Cluster

### Chart Version

5.5.0

### Environment

Amazon Web Services

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by harshitsinghvi22** [comment]
@psolarcz as of now in order to create a cluster you will need to install neo4j 3 times or the number of instances in a cluster you need.

You can do something like this as per helm 
https://helm.sh/docs/helm/helm_dependency/

```
dependencies:
  - name: neo4j
    alias: server1
    version: 5.10.0
    repository: https://helm.neo4j.com/neo4j
  - name: neo4j
    alias: server2
    version: 5.10.0
    repository: https://helm.neo4j.com/neo4j
  - name: neo4j
    alias: server3
    version: 5.10.0
    repository: https://helm.neo4j.com/neo4j
```
and have each server values.yaml defined in your chart values.yaml under its own section

https://helm.sh/docs/chart_template_guide/subcharts_and_globals/

Any reason why it is marked as a bug @psolarcz  ?

**Comment by ojhughes** [comment]
You can create a sub chart that uses Neo4j as a dependency, for example;

**chart.yaml**
```
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: neo4j
    alias: db-server1
    version: 5.10.0
    repository: https://helm.neo4j.com/neo4j
  - name: neo4j
    alias: db-server2
    version: 5.10.0
    repository: https://helm.neo4j.com/neo4j
  - name: neo4j
    alias: db-server3
    version: 5.10.0
    repository: https://helm.neo4j.com/neo4j
```

**values.yaml**
```
neo4jName: &neo4jName "my-neo4j-subchart"
db-server1:
  disableLookups: true
  fullnameOverride:  "db-server1"
  neo4j:
    name: *neo4jName
    acceptLicenseAgreement: "yes"
    edition: enterprise
    minimumClusterSize: 3
    passwordFromSecret: test-auth
  volumes:
    data:
      mode: defaultStorageClass
  services:
    neo4j:
      enabled: false
db-server2:
  disableLookups: true
  fullnameOverride: "db-server2"
  neo4j:
    name: *neo4jName
    acceptLicenseAgreement: "yes"
    edition: enterprise
    minimumClusterSize: 3
    passwordFromSecret: test-auth
  volumes:
    data:
      mode: defaultStorageClass
  services:
    neo4j:
      enabled: false
db-server3:
  disableLookups: true
  fullnameOverride: "db-server3"
  neo4j:
    name: *neo4jName
    acceptLicenseAgreement: "yes"
    edition: enterprise
    minimumClusterSize: 3
    passwordFromSecret: test-auth
  volumes:
    data:
      mode: defaultStorageClass
  services:
    neo4j:
      enabled: false
```
