### ISSUE TITLE
[Bug]: "Secret already exists" when creating a cluster using Terraform 

### ISSUE THREAD

**Issue by colintkn** [neo4j/helm-charts#210]
### What happened?

I'm deploying a cluster using Terraform by setting the count of the `helm_release` to deploy the release 3 times. My releases are named as `neo4j-0`, `neo4j-1`, `neo4j-2`

I get the error: 
`failed to create resource: secrets "neo4j-auth" already exists`

Based on the helm chart, the naming of the secrets should be i.e. `neo4j-1-auth`. Am I missing something or is this a bug. 

Here's the `values.yaml`
```
---
# Configuration https://neo4j.com/docs/operations-manual/current/kubernetes/configuration/
neo4j:
  name: neo4j
  minimumClusterSize: 3
  resources:
    cpu: "0.5" 
    memory: "2Gi"
  password: <password>
  edition: "enterprise"
  acceptLicenseAgreement: "yes"

services:
  neo4j:
    enabled: false

image:
  customImage: "605977352189.dkr.ecr.ap-southeast-1.amazonaws.com/docker.io/library/neo4j:5.9.0"
  imagePullPolicy: Always
```

### Chart Name

Cluster

### Chart Version

5.5.0

### Environment

Amazon Web Services

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
