### ISSUE TITLE
Argocd helm neo4j cluster , shared resources issues fix

### ISSUE THREAD

**Issue by anieo** [neo4j/helm-charts#240]
### **Is your feature request related to a problem? Please describe.**

well, This is not a feature request but more like a fix to a problem, i just wanted to add it in issues for future refrence if anyone faced this issue

### **the problem is :**

if you are trying to install neo4j cluster with helm + argocd and have auth enabled and loadbalancer enabled. you will face an issue where each argo-cd application for each cluster node will fight to add a label or annotation representing the argocd application name 
like this 
![image](https://github.com/neo4j/helm-charts/assets/27463944/2d09368e-9565-4ace-8614-0d1814f6073c)
![image](https://github.com/neo4j/helm-charts/assets/27463944/0b22e07f-9a35-4be6-bd68-898678bd9722)
the helm chart handles helm labels and annotations but doesn't handle argocd annotations which is completely reasonable 

### **work around**

using one of argocd feature [Diffing Customization](https://argo-cd.readthedocs.io/en/stable/user-guide/diffing/)
you can add this section to each argocd application and it will stop argocd for trying to solve the label issue

```YAML
spec:
  ignoreDifferences:
  - group: "*"
    kind: Secret
    name: cluster-auth
    namespace: neo4j
    jsonPointers:
    - /metadata/labels/argocd.argoproj.io~1instance
  - group: "*"
    kind: Service
    name: cluster-lb-neo4j
    namespace: neo4j
    jsonPointers:
    - /metadata/labels/argocd.argoproj.io~1instance
```
