### ISSUE TITLE
Unable to load plugins using helm charts

### ISSUE THREAD

**Issue by holleyism** [neo4j/helm-charts#3]
Steps to reproduce:

Using the basic value.yaml with a plugin volume defined as per [documents](https://neo4j.com/docs/operations-manual/current/kubernetes/), run helm install neo4j-release neo4j/neo4j-standalone -f values.yaml
copy the apoc jar to the /plugins container on the pod.
restart the pod.
plugins are not loaded
Expected behavior

Plugins should be loaded

Neo4j image tag being used, 4.4.3

Operating system: ubuntu

The helm charts do not provide a means to override the plugins folder configuration, however if I manually edit the neo4j configmap and add dbms.directories.plugins: /plugins, it is loaded correctly.

The default appears to be /var/lib/neo4j/plugins which is not a directory backed by a persistent volume

It also appears not possible to add a volumeMount to the values file for plugins as that is overridden because of the volume definition (see _volumeTemplate.tpl).

**Comment by varunagarwal454** [comment]
@holleyism did you get any solution to above problem ? am also facing this issue

**Comment by holleyism** [comment]
@varunagarwal454 I just update the configmap after installing currently.

**Comment by harshitsinghvi22** [comment]
Apologies for the delay in response @holleyism 

The helm charts do not provide a means to override the plugins folder configuration, however if I manually edit the neo4j configmap and add dbms.directories.plugins: /plugins, it is loaded correctly.

--> @holleyism  ..u can set the plugins directory in values.yaml under config section.

```
config:
  dbms.directories.plugins: "/var/lib/neo4j/plugins"
  dbms.security.procedures.unrestricted: "apoc.*"  
  dbms.config.strict_validation: "false"
  dbms.security.procedures.allowlist: "gds.*,apoc.*"

apoc_config:
  apoc.trigger.enabled: "true"
  apoc.jdbc.test.url: "jdbc:foo:bar"
  apoc.import.file.enabled: "true"

```
Also we have introduced a new section called apoc_config under values.yaml to define apoc config
https://neo4j.com/docs/operations-manual/current/kubernetes/configuration/#operations-using-apoc-core
