### ISSUE TITLE
Add support for pod affinity

### ISSUE THREAD

**Issue by bskim45** [neo4j/helm-charts#32]
Currently, the helm chart only supports pod anti-affinity. It would be nice to support [pod affinity](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity), which is useful to schedule Pods and PV within the specific AZ.

ex. 
```yaml
podSpec:
  podAntiAffinity: true

  podAffinity:  # default {}
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: failure-domain.beta.kubernetes.io/zone
            operator: In
            values:
              - us-central1-a
```
