### ISSUE TITLE
[Bug]: neo4j-standalone - duplicate mapping key at ConfigMap

### ISSUE THREAD

**Issue by chlumper** [neo4j/helm-charts#36]
### Contact Details

c.lumper@tributech.io

### What happened?

If you render the [neo4j-standalone](https://github.com/neo4j/helm-charts/tree/dev/neo4j-standalone) helm chart using `helm template -f values.yaml neo4j-test .`
using a minimal `values.yaml`:
```
neo4j:
  enabled: true
  volumes:
    data:
      mode: "volume"
      volume:
        emptyDir:
          medium: Memory
```

it leads to a duplicate mapping key for `dbms.directories.import` in the ConfigMap

```yaml
# Source: neo4j-test/charts/neo4j/templates/neo4j-config.yaml
# Default Neo4j config values, these are overridden by user-provided values in neo4j-test-user-config
apiVersion: v1
kind: ConfigMap
metadata:
  name: "neo4j-test-default-config"
  namespace: "default"
  labels:
    app: "neo4j"
data:
  # Neo4j defaults
  dbms.directories.import: import # <---- DUPLICATE
  dbms.tx_state.memory_allocation: ON_HEAP
  dbms.connector.bolt.enabled: 'true'
  dbms.connector.http.enabled: 'true'
  dbms.connector.https.enabled: 'false'
  dbms.tx_log.rotation.retention_policy: 1 days
  dbms.windows_service_name: neo4j

  # ...

  # Import
  dbms.directories.import: "/import" # <---- DUPLICATE
```
which is invalid according to the [yaml spec](https://yaml.org/spec/1.2.2/#3211-nodes) and leads to the following error at the cd tool [flux](https://fluxcd.io/):
```
Helm install failed: error while running post render on files:
    map[string]interface {}(nil): yaml: unmarshal errors:
        line 38: mapping key "dbms.directories.import" already defined at line 14
```
(Similar issues at other helm charts with flux: https://github.com/fluxcd/helm-controller/issues/283)

---
Expected behavior:

Valid yaml with single `dbms.directories.import` entry in the ConfigMap to allow deplyoment with cd tool flux.

---

Relevant parts at the helm chart:
  * configmap - neo4j defaults:
https://github.com/neo4j/helm-charts/blob/c9c9bcf038ca328e56fbb1d2305cfb57c1f3d3ae/neo4j-standalone/templates/neo4j-config.yaml#L74-L76
  * configmap - import:
https://github.com/neo4j/helm-charts/blob/c9c9bcf038ca328e56fbb1d2305cfb57c1f3d3ae/neo4j-standalone/templates/neo4j-config.yaml#L130-L133
  * conf:
https://github.com/neo4j/helm-charts/blob/c9c9bcf038ca328e56fbb1d2305cfb57c1f3d3ae/neo4j-standalone/neo4j-community.conf#L19-L22

---

As a workaround I tried to disable the "import volume" with the following `values.yaml` entry without any luck, due to merging behavior of helm and the template conditional.
```yaml
neo4j:
  volumes:
    import:
      enabled: false
```
or
```yaml
neo4j:
  volumes:
    import: {}
```

---

Tested with neo4j-standalone version `4.4.3` and `4.4.5`.

### Chart Name

Standalone

### Chart Version

4.4.3

### Environment

Microsoft Azure

### Relevant log output

```shell
Helm install failed: error while running post render on files:
    map[string]interface {}(nil): yaml: unmarshal errors:
        line 38: mapping key "dbms.directories.import" already defined at line 14
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by harshitsinghvi22** [comment]
Hi @chlumper 

The values.yaml posted looks incorrect

```
neo4j:
  enabled: true
  volumes:
    data:
      mode: "volume"
      volume:
        emptyDir:
          medium: Memory
```

there is no enabled or volumes object under neo4j.

Can you please check and provide the correct and complete values.yaml ?

Thanks,
Harshit

**Comment by harshitsinghvi22** [comment]
Hi @chlumper 

Was able to reproduce the issue with the below yaml.

```
volumes:
    data:
      mode: "volume"
      volume:
        emptyDir:
          medium: Memory
```

Will take a look and do the necessary fix.

Thanks for bringing this to our attention. Appreciate your time and effort in raising this issue.

Regards,
Harshit

**Comment by chlumper** [comment]
> Hi @chlumper
> 
> The values.yaml posted looks incorrect
> 
> ```
> neo4j:
>   enabled: true
>   volumes:
>     data:
>       mode: "volume"
>       volume:
>         emptyDir:
>           medium: Memory
> ```
> 
> there is no enabled or volumes object under neo4j.
> 
> Can you please check and provide the correct and complete values.yaml ?
> 
> Thanks, Harshit

Sorry the sub entry `neo4j` and `enabled` is just there since its used in an umbrella chart like this:
```yaml
apiVersion: v2
name: neo4j-test
description: A Helm chart to test neo4j
type: application
version: 0.0.1
appVersion: "0.0.1"

dependencies:
  - condition: neo4j.enabled
    name: neo4j-standalone
    version: 4.4.3
    repository: https://helm.neo4j.com/neo4j
    alias: neo4j
```

But as you denoted that's not causing the actual problem.

Thanks a lot for taking a look!
