### ISSUE TITLE
How can we specify apoc conf ?

### ISSUE THREAD

**Issue by AdrienLemaire** [neo4j/helm-charts#39]
In the previous helm `neo4j-contrib/neo4j-helm`, it seems like we could add an `apoc.conf` file to the neo4j pod as a ConfigMap, configured via `core.additionalVolumes` and `core.additionalVolumeMounts`.
But the new helm documentation doesn't mention these keys anymore. 

What would be the appropriate way to specify an apoc settings now ? Wanting to add `apoc.trigger.enabled = true` to my standalone neo4j server.

**Comment by harshitsinghvi22** [comment]
Hi @AdrienLemaire ,

Thanks for raising this question with us.

Currently , we are in the process of providing support to apoc.conf however until then you can specify apoc configs in your values.yaml under config section.



```
config:
  dbms.directories.plugins: "/var/lib/neo4j/plugins"
  dbms.security.procedures.unrestricted: "apoc.*"  
  apoc.trigger.enabled: "true"
  dbms.config.strict_validation: "false"

```

Here , I have assumed that you have placed the apoc plugin in /var/lib/neo4j/plugins location
