### ISSUE TITLE
Add support for configuring Service ExternalTrafficPolicy Settings

### ISSUE THREAD

**Issue by shugotek** [neo4j/helm-charts#400]
**Is your feature request related to a problem? Please describe.**
Currently we deploy Neo4J in a k8s cluster on EKS, SVC is redirected by NLB and NodePort type but "ExternalTrafficPolicy" is set on Local.
So to be able to use it, we need to set "ExternalTrafficPolicy" on Cluster.

**Describe the solution you'd like**
Add possibility to edit "ExternalTrafficPolicy" in Helm chart, for example : 
```
services:
  neo4j:
    spec:
      type: NodePort
      externalTrafficPolicy: Cluster
```
