### ISSUE TITLE
[Bug]: Unable to persist plugins data in mount point /var/lib/neo4j/plugins in neo4j container 

### ISSUE THREAD

**Issue by varunagarwal454** [neo4j/helm-charts#49]
### Contact Details

varun.agarwal2@inter.ikea.com

### What happened?

Hi, I am deploying a standalone instance of neo4j as per instructed here  -> https://neo4j.com/docs/operations-manual/current/kubernetes/quickstart-standalone/. Everything install successfully .

**helm install my-neo4j-release neo4j/neo4j-standalone -f my-neo4j.values.yaml**

I want to install some third party plugins in my neo4j container and want them to persist after restarting the container ( in order for them to apply successfully ) To be more precise i am following this -> `https://neo4j.com/labs/neosemantics/4.0/install/` installation. But after restarting the `container` , all JAR vanishes . 

So I mounted the "plugin" volume to "data"  volume with "share" mode. My neo4j.values.yaml looks like this ->

neo4j:
  resources:
    cpu: "0.5"
    memory: "2Gi"

volumes:
  data:
    mode: "defaultStorageClass"
    defaultStorageClass: 
      requests:
        storage: 2Gi

  plugins:
    mode: "share"
    share:
      name: "data" 

It seems like helm-neo4j deployment create all Volume mount at root path ,  as per document -> https://neo4j.com/docs/operations-manual/current/kubernetes/persistent-volumes/ . But neo4j container is taking "var/lib/neo4j/plugins" or "${NEO4J_HOME}/plugins" mount point into consideration for any plugins installation and also restarting the container isn't persisting any plugins in that mount point, cause volume **plugins**   is referring to "/plugins" instead of "var/lib/neo4j/plugins"

Do we have any workaround for such kind of situation ?

### Chart Name

Standalone

### Chart Version

4.3.9 (Standalone only)

### Environment

Local Machine

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xiaoFine** [comment]
```yaml
...
config:
  dbms.directories.plugins: "/plugins"
...
```
defining the path of pulgins in values.yaml works for me

**Comment by varunagarwal454** [comment]
@xiaoFine ->
It seems to work for me. Though there is another neo4j configuration , i need to put into neo4j container 
**dbms.unmanaged_extension_classes=n10s.endpoint=/rdf** 

As per this doc - https://neo4j.com/labs/neosemantics/4.0/install/ , it should be place under - **<NEO_HOME>/conf/neo4j.conf**  , followed by restart .But that path seems to be non-persistent when pod restart.  Have you come across such configuration requirement?

**Comment by xiaoFine** [comment]
I just put all my configs here in the values.yaml:
```
config:
  dbms.config.strict_validation: "true"
  dbms.security.procedures.unrestricted: "gds.*,apoc.*,n10s.*"
  dbms.security.procedures.allowlist: "apoc.*,gds.*,n10s.*"
  dbms.unmanaged_extension_classes: "n10s.endpoint=/rdf"
  dbms.connector.bolt.enabled: "true"
  dbms.connector.bolt.listen_address: "0.0.0.0:7687"
  dbms.connector.http.enabled: "true"
  dbms.connector.http.listen_address: "0.0.0.0:7474"
  dbms.connector.https.enabled: "true"
  dbms.connector.https.listen_address: "0.0.0.0:7473"
  dbms.logs.user.stdout_enabled: "true"
  dbms.directories.plugins: "/plugins"
```
maybe neo4j.conf is supposed to be replaced by the `config` in the values.yaml when comes to k8s deploying.

hope helps

> @xiaoFine -> It seems to work for me. Though there is another neo4j configuration , i need to put into neo4j container **dbms.unmanaged_extension_classes=n10s.endpoint=/rdf**
> 
> As per this doc - https://neo4j.com/labs/neosemantics/4.0/install/ , it should be place under - **<NEO_HOME>/conf/neo4j.conf** , followed by restart .But that path seems to be non-persistent when pod restart. Have you come across such configuration requirement?
