### ISSUE TITLE
[Bug]: charts does not support alias in parent charts

### ISSUE THREAD

**Issue by quertenmont** [neo4j/helm-charts#76]
### Contact Details

loic.quertenmont@gmail.com

### What happened?

I want to include this chart in a bigger chart via chart Dependencies of that kind:
```
dependencies:
  - name: neo4j-standalone
    alias: neo4j
    condition: neo4j.enabled
    version: "4.4.8"
    repository: "https://helm.neo4j.com/neo4j"
```

unfortunately, it looks like the template scripts are broken because of this.
One of the error I am first facing is this one:
```
helm upgrade --install my-app app  -f values.yaml
Error: UPGRADE FAILED: template: cage/charts/neo4j/templates/neo4j-statefulset.yaml:66:33: executing "cage/charts/neo4j/templates/neo4j-statefulset.yaml" at <include "neo4j.initChmodContainer" .>: error calling include: template: cage/charts/neo4j/templates/_volumeTemplate.tpl:102:24: executing "neo4j.initChmodContainer" at <include "neo4j.initChmodScript" .>: error calling include: template: cage/charts/neo4j/templates/_volumeTemplate.tpl:130:8: executing "neo4j.initChmodScript" at <index $spec $spec.mode>: error calling index: value is nil; should be of type string
```
my values file is like this:
```
neo4j:
  enabled: true
  neo4j:
    acceptLicenseAgreement: 'yes'
    edition: enterprise
    password: xxx
  volumes:
    data:
      mode: "dynamic"
      dynamic:
        accessModes:
        - ReadWriteOnce
        requests:
          storage: 20Gi
        storageClassName: persistent
```

If I remove the alias and rename my value block from "neo4j" to "neo4j-standalone" I can deploy without issues.
It would be good to fix the tempalte for this (rather common) use case.

### Chart Name

Standalone

### Chart Version

4.4.3

### Environment

Issue seen on all the cloud providers (GCP , AWS , AKS)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
